package:
  name: pascalx
  version: "0.0.4"

source:
  url: https://github.com/BergmannLab/PascalX/archive/refs/tags/v0.0.4.tar.gz
  sha256: e0b8fcfe3ffa242afb4744359591e906d2243eb842e926f80d9c07a8a46d1ecd

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('pascalx', max_pin=None) }}

requirements:
  build:
    - python >=3,<3.10
    - setuptools
    - pip
    - cffi
    - make
    - {{ compiler('cxx') }}
  host:
    - python >=3,<3.10
    - setuptools
    - pip
    - cffi
  run:
    - python >=3,<3.10
    - cffi >=1.0.0
    - matplotlib-base !=3.6.1,>=3.1
    - sortedcontainers >=2.1.0
    - tqdm >=4.43.0
    - scipy >=1.4.0,<1.11.0
    - numpy >=1.18.0,<1.25.0
    - seaborn >=0.11.0
    - progressbar >=2.5
    - fastnumbers >=3.1.0

test:
  imports:
    - PascalX  # Assuming PascalX is the import name; adjust if necessary
  commands:
    - pascalx -h  # Make sure this is a valid test command for your package

about:
  home: https://github.com/BergmannLab/PascalX
  license: AGPL-3.0-or-later
  license_file: LICENSE
  summary: "PascalX is a python3 library for high precision gene and pathway scoring for GWAS summary statistics"

extra:
  notes: "This package is built from the source available at the GitHub repository."

